#!/data/data/com.termux/files/usr/bin/bash
set -e 

# Files
LG="/data/data/com.termux/files/usr/etc/locale.gen"
EE="/data/data/com.termux/files/usr/etc/default/locale"

# Sanitize environnement
LC_ALL=zh_CN.UTF-8
LANG=zh_CN.UTF-8

        # Comment previous defined locales
        sed -i -e 's/^ *[a-zA-Z]/# &/' $LG

        # Get list of supported locales
        if [ -f "/data/data/com.termux/files/usr/share/i18n/SUPPORTED" ] ; then
            SUPPORTED_LOCALES="$(sed -e '/^[a-zA-Z]/!d' -e 's/ *$//g' /data/data/com.termux/files/usr/share/i18n/SUPPORTED /data/data/com.termux/files/usr/share/i18n/SUPPORTED | sort -u)"
        else
            SUPPORTED_LOCALES="$(sed -e '/^[a-zA-Z]/!d' -e 's/ *$//g' /data/data/com.termux/files/usr/share/i18n/SUPPORTED | sort -u)"
        fi

        # Make sure all locales exist in locales.gen
        echo "$SUPPORTED_LOCALES" | while read locale ; do
           if ! grep -q "^[# ]*$locale *\$" $LG; then 
             echo "# $locale" >> $LG
           fi
        done

    # Update requested locales if locales-all is not installed
    if dpkg-query -W -f='${db:Status-Abbrev}' locales-all 2>/dev/null | grep -q '^i' ; then
        echo "locales-all installed, skipping locales generation"
    else
        locale-gen
    fi



exit 0
